# Generated by Django 3.2 on 2021-04-07 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='queue',
            options={'verbose_name': 'Черга', 'verbose_name_plural': 'Черги'},
        ),
    ]
