# Generated by Django 3.2 on 2021-04-07 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_alter_queue_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор черги'),
        ),
        migrations.AddField(
            model_name='queue',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Час початку заняття'),
            preserve_default=False,
        ),
    ]
