# Generated by Django 3.2 on 2021-04-07 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210407_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='uuid',
            field=models.UUIDField(blank=True, default=None, unique=True, verbose_name='Другорядний первинний ключ'),
            preserve_default=False,
        ),
    ]
