# Generated by Django 3.2 on 2021-04-07 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_unigroup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unigroup',
            options={'verbose_name': 'Університетська група', 'verbose_name_plural': 'Університетські групи'},
        ),
        migrations.AddField(
            model_name='user',
            name='uni_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_profile.unigroup', verbose_name='Університетська група'),
        ),
    ]
