# Generated by Django 3.2 on 2021-04-08 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_auto_20210407_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unigroup',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.faculty', verbose_name='Факультет'),
        ),
    ]
